# Generated by Django 4.2.8 on 2026-05-17 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_applications_scholarships_rename_genders_roles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('grade_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=4)),
                ('semester', models.CharField(max_length=50)),
                ('school_year', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scholar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.scholarprofiles')),
            ],
            options={
                'db_table': 'tbl_grades',
            },
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('announcement_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.users')),
            ],
            options={
                'db_table': 'tbl_announcements',
            },
        ),
    ]
