# Generated by Django 4.2.8 on 2026-05-16 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_users_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('application_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('renewal', 'Renewal')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_applications',
            },
        ),
        migrations.CreateModel(
            name='Scholarships',
            fields=[
                ('scholarship_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slots', models.IntegerField()),
                ('eligibility', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_scholarships',
            },
        ),
        migrations.RenameModel(
            old_name='Genders',
            new_name='Roles',
        ),
        migrations.RenameField(
            model_name='roles',
            old_name='gender',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='roles',
            old_name='gender_id',
            new_name='role_id',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='gender',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='users',
            name='address',
        ),
        migrations.RemoveField(
            model_name='users',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='users',
            name='contact_number',
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='roles',
            table='tbl_roles',
        ),
        migrations.CreateModel(
            name='ScholarProfiles',
            fields=[
                ('scholar_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('school', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('year_level', models.CharField(max_length=20)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='scholar_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crud.users')),
            ],
            options={
                'db_table': 'tbl_scholar_profiles',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('document_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.applications')),
            ],
            options={
                'db_table': 'tbl_documents',
            },
        ),
        migrations.AddField(
            model_name='applications',
            name='scholar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.scholarprofiles'),
        ),
        migrations.AddField(
            model_name='applications',
            name='scholarship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.scholarships'),
        ),
    ]
