# Generated by Django 4.2.8 on 2026-05-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_grades_announcements'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
