# Generated by Django 4.2.8 on 2026-05-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_users_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='scholarprofiles',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
