# Generated by Django 4.2.8 on 2026-05-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_users_address_users_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarships',
            name='min_gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
