# Generated by Django 4.2.8 on 2026-05-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_scholarships_min_gpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarships',
            name='min_gpa',
        ),
        migrations.AddField(
            model_name='scholarships',
            name='required_gpa',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=4),
        ),
    ]
