# Generated by Django 4.2.8 on 2026-05-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_remove_scholarships_min_gpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='units',
            field=models.DecimalField(decimal_places=1, default=3.0, help_text='Credit units for this subject.', max_digits=4),
        ),
        migrations.AddField(
            model_name='scholarprofiles',
            name='maintaining_grade',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Maximum allowable grade (Philippine system). Grades above this are considered Failed.', max_digits=4),
        ),
    ]
