# Generated by Django 4.2.8 on 2026-05-21 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_grades_units_scholarprofiles_maintaining_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='target_user',
            field=models.ForeignKey(blank=True, help_text='If set, only this user can see the announcement. Leave blank for public.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_announcements', to='crud.users'),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_announcements', to='crud.users'),
        ),
    ]
