# Generated by Django 4.2.8 on 2026-05-21 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_announcements_target_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarprofiles',
            name='photo',
        ),
    ]
