# Generated by Django 4.2.8 on 2026-05-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0012_remove_scholarprofiles_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarships',
            name='required_gpa',
        ),
        migrations.AddField(
            model_name='scholarships',
            name='gpa_requirement',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum GPA required to apply. Leave blank if no GPA requirement.', max_digits=4, null=True),
        ),
    ]
