# Generated by Django 4.2.8 on 2026-05-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0013_remove_scholarships_required_gpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
