# Generated by Django 4.2.8 on 2026-05-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0014_users_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
