# Generated by Django 4.2.8 on 2026-05-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0015_alter_users_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarprofiles',
            name='phone',
        ),
    ]
